
"use client";

import { createContext, useContext, useState } from 'react';

// Hardcoded initial data
const initialQuizzes = [
  { id: 1, title: 'Life Cycles of a Plant', subject: 'Science', questions: [{imageUrl: '/placeholder.svg', description: 'A seed is planted.'}] },
  { id: 2, title: 'The Solar System', subject: 'Science', questions: [] },
  { id: 3, title: 'World War II', subject: 'History', questions: [] },
  { id: 4, title: 'Algebra Basics', subject: 'Maths', questions: [] },
];

const QuizContext = createContext();

export function QuizProvider({ children }) {
  const [quizzes, setQuizzes] = useState(initialQuizzes);

  const addQuiz = (quiz) => {
    // In a real app, the ID would be generated by the database
    const newQuiz = { ...quiz, id: Date.now(), questions: quiz.questions || [] };
    setQuizzes(prevQuizzes => [...prevQuizzes, newQuiz]);
  };
  
  const getQuizById = (id) => {
    return quizzes.find(quiz => quiz.id === parseInt(id));
  };

  return (
    <QuizContext.Provider value={{ quizzes, addQuiz, getQuizById }}>
      {children}
    </QuizContext.Provider>
  );
}

export function useQuiz() {
  return useContext(QuizContext);
}
